### ISSUE TITLE
getIntersectionUU(S2CellUnion,S2CellUnion) bombing out

### ISSUE THREAD

**Issue by tinykov** [vekexasia/nodes2-ts#1]
Hi Andrea

I hope you are doing well. I have been using your nodes2ts npm package and noticed that 
i couldn't get an intersection of two s2cell unions due to this type error:-

TypeError: Cannot read property 'rangeMax' of undefined
    at S2CellUnion.getIntersectionUU (/Users/tinyiko/node_modules/nodes2ts/dist/S2CellUnion.js:254:65)
    at makeS2Union (/Users/tinyiko/WebstormProjects/GoSwift/goSwift-Dispatch/shebeen/s2UnionTest.js:32:15)
    at Object.<anonymous> (/Users/tinyiko/WebstormProjects/GoSwift/goSwift-Dispatch/shebeen/s2UnionTest.js:35:1)

See my attached example and advice if there is something i am doing wrong.  Note that the 1st element in 
cellId_one and cellIds_two is exactly the same. 

Regards
Tinyiko
-------------------------

/**
 * Created by tinyiko on 2017/04/12.
 */

var s2 = require("nodes2ts");

var cellId_one = "2203840834468577280,2203676182602317824,2203694187105222656,2203734542617935872,2203734645697150976,2203699392605585408";
var cellIds_two = "2203840834468577280,2203682229916270592,2203804700908716032,2203692812715687936,2203846933322137600";

function arrayCopy(oldArray){
    return JSON.parse(JSON.stringify(oldArray))
}

makeS2Union = function(){

    var unionOne = new s2.S2CellUnion();
    var cell_ids = cellId_one.split(',');
    console.log(cell_ids);
    unionOne.initFromIds(cell_ids);

    var unionTwo = new s2.S2CellUnion();
    var cell_ids2 = cellIds_two.split(',');
    console.log(cell_ids2);
    unionTwo.initFromIds(cell_ids2);

    var newUnion = new s2.S2CellUnion();
    newUnion.getUnion(unionOne,unionTwo);

    console.log("new union = " + newUnion.cellId);

    var newUnion2 = new s2.S2CellUnion();
    newUnion2.getIntersectionUU(unionOne,unionTwo);
}

makeS2Union();

**Comment by vekexasia** [comment]
Hello @tinykov ,

thank you for reaching out. Indeed there were many issues with S2CellUnion that were not covered by any test.

I've published version 1.1.8 to npm that brings a fix to your and other related S2CellUnion bugs. 

Newly created tests compares java results for union and intersection of randomly created Cell unions against this library :)

**Comment by tinykov** [comment]
Thanks Andrea

Works like a charm. Really appreciate your swift response. We will test
more features
of the library and will stay in touch should we have any more questions or
issues.

Great piece of work and please keep it up.

Regards
Tinyiko

**Comment by vekexasia** [comment]
@tinykov  no problem :)
