### ISSUE TITLE
Question: Why use Decimal.js?

### ISSUE THREAD

**Issue by andrezsanchez** [vekexasia/nodes2-ts#10]
I'd be interested in knowing why a high-precision number library was chosen for this port. I've perused through the Go version (one of the official versions) and it doesn't seem to be using a high-precision math library, it seems to just use f64. JavaScript is guaranteed to always use 64-bit precision floats, so it's unclear to me why this is being used for floats given the performance penalty (which I am encountering in my application).

**Comment by vekexasia** [comment]
Hey @andrezsanchez 
js can have some issues when dividing numbers i didn't want to risk.

**Comment by andrezsanchez** [comment]
What are some of those issues? JavaScript uses standard 64-bit IEEE 754 floating point numbers. There are no issues in JS that there aren't inherently in other programming languages like C++ or Java.

Furthermore, the original library makes assumptions about the format of the floats being used. I would be more wary of converting back and forth between a decimal floating point representation and a binary one, when the authors originally designed this for binary only.

**Comment by dpieri** [comment]
To add some more context, we're using `nodes2-ts` in a realtime app where the extra precision is not worth the performance penalty of decimal.js. We are considering forking `nodes2-ts` to remove decimal.js but wanted to ask first to see if there are any issues we're not thinking about.

**Comment by vekexasia** [comment]
To be honest i don't remember why I made that choice. I guess I encountered some js math quircks. 

If some of you can manage to remove decimal and let tests pass i'll be more than happy to merge. Unfortunately nowadays I've very little free time and I cannot do it :(

**Comment by vekexasia** [comment]
Hi there, after 1.5y I re-picked up this project and ditched decimal.js performance boost is 10x
