### ISSUE TITLE
Publish 1.1.11?

### ISSUE THREAD

**Issue by rh389** [vekexasia/nodes2-ts#12]
Hi,

Would you mind pushing a new release with the region coverer fix included? (https://github.com/vekexasia/nodes2-ts/commit/1952d8c1f6cb4a862731ace2d5f74d472ec22e55)

Users of one of my libs are running into this issue (https://github.com/rh389/dynamodb-geo.js/issues/8) so I'd like to update its dependencies.

Thanks!

**Comment by vekexasia** [comment]
Please check 2.0.0

**Comment by Bersaelor** [comment]
@vekexasia Sorry to resurrect this thread, I tried using the `2.0.0` but I got an error in
https://github.com/vekexasia/nodes2-ts/blob/master/src/S2.ts#L75
"Error: method not written yet".

I'm a little stumped, Is this an oversight where someone forgot that line before publishing or is more work needed there?
