### ISSUE TITLE
getter methods for cell id in S2CellId and S2Cell

### ISSUE THREAD

**Issue by tinykov** [vekexasia/nodes2-ts#2]
getter methods for key, id and level of S2CellId and S2CellId appears not working.
Currently have to use a workaround like below to get the Id. 

var s2cell = new s2.S2CellId.fromPoint(s2Latlong.toPoint(lat,lon));
var s2cell_str = s2cell.id.toString();

s2cell.id returns 
- Long { low: -1232523503, high: 513111008, unsigned: false }
s2cell.id()  returns

s2cell.id()
- TypeError: s2cell.id is not a function

- Also methods to convert back to LatLngs once i have a S2CellId/S2Cell especially for leaf cells. the current toLatLng() gives error: - s2_cell.toLatLng is not a function

**Comment by vekexasia** [comment]
That's expected.

Il 15 apr 2017 16:55, "Tinyiko Valoyi" <notifications@github.com> ha
scritto:
