### ISSUE TITLE
Appreciation / Question on direction

### ISSUE THREAD

**Issue by liang3404814** [vekexasia/nodes2-ts#31]
Hi nodes2ts!

First of all, I want to say 🔥 🔥 🔥 thank you 🔥 🔥 🔥  to all the maintainers for all your work on the project!  S2 cells are complex, and your hard work opens the door to usage on the web natively, opening lots of doors and possibilities. 

As an introduction, my name is Ang, and I'm a software engineer currently working at Airbnb.  We are evaluating S2 cells as the basis of a tile coordinate system that enable us to cache some features that we show on our map in the browser.  This library feels like a great fit because it implements most of the important classes and features present in the reference C++ library, and unlike many other similar libraries, it's TS-based, so it can run in the browser. 

My ideal outcome is to be able to reliably cover a given region with S2 cells, and verify the output is in parity with other implementations such as https://github.com/google/s2-geometry-library-java. (I know some existing tests are using data from the Java implementation)

With the above outcome in mind, here are a number of improvements that I'd like to make:
1. Adding more test coverage to `S2CellUnion`
2. Creating tests for `S2RegionCoverer`
3. Fixing https://github.com/vekexasia/nodes2-ts/issues/16 (I _think_ I have identified the cause)
(I can open these as separate issues / address them in existing threads if that would be preferable.)

I will be able to spend time on these outlined issues, but before I start coding, I just want to make sure that we agree on a direction to go forward, and that my changes will actually be merged and published in a timely manner. (I also offer to help with general maintenance of the repository, like triaging issues or handling dependency updates, if needed)

Please let me know if you are open to a quick video call, as I'm more than happy for us to get to know each other, and discuss the project. Personally this is my preferred way to self-introduce, but if you prefer other forms of communication, I'm happy to continue the conversation in whichever way that's most convenient.

Again, thank you very much to all the contributors for working on this project, and please let me know what you think 🙏 🙏 🙏

**Comment by vekexasia** [comment]
Hey liang, thanks for your message and appreciation words.

I initially wrote this library in order to have s2 run in the browser for a project of mine. As soon as the project ended I didnt want to spend more time on this. 

If you feel like to help, fix bugs, write some tests, or upgrade dependencies you can definitely go ahead. I'll do my best to review merge requests and merge them in a timely matter.

If you want to have a call you can add me on telegram @el_bau so we can coordinate.
