### ISSUE TITLE
performance issue with getCovering of regioncoverer

### ISSUE THREAD

**Issue by tinykov** [vekexasia/nodes2-ts#7]
Is there a way to improve performance of the getCoveringCells (S2RegionCoverer) with an S2Cap of  100 Max cells with min level at 12 and max level at 16. Currently this seems to take over 220 ms. Would be great if performance can be improved to tens of milliseconds.

**Comment by vekexasia** [comment]
hello @tinykov unfortunately i don't have the time needed to take a look at the code and find an eventual spot for optimizing things.
