### ISSUE TITLE
Improve docs: Api Reference

### ISSUE THREAD

**Issue by Birowsky** [vekexasia/nodes2-ts#8]
I was looking even for the reference Java implementation api reference. No matches. Maybe I need to step up my googling game.. :}

Anyways, how does one get familiar to the api of this library?

**Comment by vekexasia** [comment]
Hey @Birowsky the APIs are basically the same as the java library. Code is basically a 1:1 so you can either read the java version or the ts version.

**Comment by vekexasia** [comment]
If you're willing to add some automatic jsdoc generation please do :)

**Comment by Birowsky** [comment]
Wait, where is the Java documentation again? Or are you saying 'just read the ts code annotations'?

**Comment by vekexasia** [comment]
Unfortunately i don't remmber any java documentation I've read the java code (And ported it here) to get it done.

What i'm suggesting you is to read ts node annotations. I don't think s2 geometry got some documentation love from Google.

**Comment by Birowsky** [comment]
Ah, thats a sad story. Thanx a lot for the port nonetheless!

**Comment by andrezsanchez** [comment]
The Go version has pretty decent documentation.

https://godoc.org/github.com/golang/geo/s2

**Comment by richardowright** [comment]
Check out https://github.com/mapbox/node-s2/blob/master/API.md .
